name: sanad
repository: https://github.com/DiggAiHH/Sanad

packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze .
    description: Run dart analyze in all packages

  test:
    run: melos exec -- flutter test
    description: Run flutter test in all packages

  build:android:
    run: melos exec --scope="*_app" -- flutter build apk --release
    description: Build Android APKs for all apps

  build:ios:
    run: melos exec --scope="*_app" -- flutter build ios --release --no-codesign
    description: Build iOS for all apps

  clean:
    run: melos exec -- flutter clean
    description: Clean all packages

  gen:
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    description: Run code generation
